#!/bin/bash

# The directory to search. Modify as necessary.
dir_to_search="/path/to/your/directory"

# Find files modified in the last 8 hours
find $dir_to_search -type f -mmin -$((60*8)) -print0 | while read -d $'\0' file
do
    # Print file path
    echo "File: $file"

    # Get owner of the file
    owner=$(ls -ld "$file" | awk '{print $3}')

    # Print owner
    echo "Owner: $owner"

    # If you have a mechanism to find out who modified the file, add that logic here
done
